---
- hosts: all

  tasks:
          - name: Copy key
            authorized_key:
               user: "{{ ansible_env['USER'] }}"
               state: present
               key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
